"""empty message

Revision ID: ad18bfda6ff5
Revises: 5bebae31683e
Create Date: 2023-01-14 18:36:03.736906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad18bfda6ff5'
down_revision = '5bebae31683e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('island', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('island', schema=None) as batch_op:
        batch_op.drop_column('map_id')

    # ### end Alembic commands ###
