"""empty message

Revision ID: fdfce6515d37
Revises: 107705eed525
Create Date: 2023-01-15 22:21:38.222308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfce6515d37'
down_revision = '107705eed525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('island', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attacked_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('island', schema=None) as batch_op:
        batch_op.drop_column('attacked_on')

    # ### end Alembic commands ###
